package com.example.han.smartlocktowifi;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.Gravity;
import android.view.MenuItem;
import android.view.View;
import android.widget.ImageButton;
import android.widget.PopupMenu;
import android.widget.PopupWindow;
import android.widget.RelativeLayout;
import android.widget.TextView;
import android.widget.Toast;

public class MainActivity extends Activity {

    int count = 0;
    private PopupWindow mPopupWindow;
    private ImageButton btn_Popup;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        btn_Popup = (ImageButton) findViewById(R.id.place_setting1);

        //        setContentView(R.layout.main_layout);
        //        ActionBar aBar = getSupportActionBar();

        //        aBar.hide();
        //        ImageButton menu_button = (ImageButton) findViewById(R.id.button_menu);
        //        ListView main_wifilist = (ListView) findViewById(R.id.main_wifilist);

        //        menu_button.setOnClickListener((View.OnClickListener) this);
        //        main_wifilist.setOnClickListener(this);

        //        ImageView ibtn = (ImageView) findViewById(R.id.menu_image);
        //        TextView ibtn = (TextView) findViewById(R.id.menu_image);
        //        registerForContextMenu(ibtn);
        //        Toast.makeText(this, "Registered...", Toast.LENGTH_SHORT).show();


        TextView wifi1 = (TextView)findViewById(R.id.wifi1);
        wifi1.setOnClickListener(new View.OnClickListener(){
            @Override
            public void onClick(View v) {
                Intent intentConfirm = new Intent();
                intentConfirm.setAction("android.settings.WIFI_SETTINGS");
                startActivity(intentConfirm);
            }
        });
    }

    @Override
    public void onBackPressed() {
        // TODO Autogenerated method stub
        super.onBackPressed();
    }


    //    @Override
    //    public void onCreateContextMenu(ContextMenu menu, View v, ContextMenu.ContextMenuInfo menuInfo) {
    //        super.onCreateContextMenu(menu, v, menuInfo);
    //        Toast.makeText(this, "Oops...", Toast.LENGTH_SHORT).show();
    //        this.getMenuInflater().inflate(R.menu.setting_menu, menu);
    //    }
    //
    //    @Override
    //    public boolean onContextItemSelected(MenuItem item) {
    //        switch (item.getItemId()) {
    //            case 1:
    //                Toast.makeText(this, "1 selected!", Toast.LENGTH_SHORT).show();
    //                break;
    //
    //        }
    //        return super.onContextItemSelected(item);
    //    }

    public void menu_open(View v) {
        PopupMenu popup = new PopupMenu(this, v);
        popup.getMenuInflater().inflate(R.menu.setting_menu, popup.getMenu());
        popup.setOnMenuItemClickListener(
                new PopupMenu.OnMenuItemClickListener() {
                    public boolean onMenuItemClick(MenuItem item) {
                        Toast.makeText(getApplicationContext(), "클릭된 팝업 메뉴" + item.getTitle(), Toast.LENGTH_SHORT).show();
                        return true;
                    }
                });
        popup.show();
    }

    public void wifi_setting_onclick(View v) {
        switch (v.getId()) {
            case R.id.place_setting1:
                View popupView = getLayoutInflater().inflate(R.layout.place_popup_window, null);
                mPopupWindow = new PopupWindow(popupView,
                        RelativeLayout.LayoutParams.WRAP_CONTENT, RelativeLayout.LayoutParams.WRAP_CONTENT);
                mPopupWindow.setAnimationStyle(1);
                mPopupWindow.showAtLocation(popupView, Gravity.CENTER, 0, 0);
                break;


            default:
                break;


        }
    }
    //    public boolean onCreateOptionMenu(Menu menu){
    //        MenuInflater inflater = getMenuInflater();
    //        inflater.inflate(R.menu.setting_menu, menu);
    //        return true;
    //    }
}
